version: 2
jobs:
  build:
    docker:
      - image: jackness1208/yyl:latest

    filters:
      branches:
        only: master

    working_directory: ~/

    steps:
      - add_ssh_keys:
        fingerprints:
          - "be:b7:23:e6:96:b5:cf:d3:ee:86:06:03:4e:fc:78:70"
      - run: git clone https://github.com/jackness1208/www.jackness.org.git
      - run: cd www.jackness.org
      - run: ls -a
      - run: yyl all --config www.jackness.org/yyl.config.js --isCommit --logLevel 2
      - run: scp www.jackness.org/dist jackness@114.215.151.192:/www/www.jackness.org
