version: 2
jobs:
  build:
    docker:
      - image: jackness1208/yyl:latest

    filters:
      branches:
        only: master

    working_directory: ~/project

    steps:
      - checkout
      - add_ssh_keys
      - run: yyl all --isCommit --logLevel 2
      - run: scp www.jackness.org/dist jackness@114.215.151.192:/www/www.jackness.org
