version: 2
jobs:
  build:
    docker:
      - image: jackness1208/yyl:latest

    filters:
      branches:
        only: master

    steps:
      - run: ls -a
      - run: yyl all --isCommit --logLevel 2
