version: 2
jobs:
  build:
    docker:
      - image: jackness1208/yyl:latest

    filters:
      branches:
        only: master
    working_directory: ~/

    steps:
      - run: echo ${CIRCLE_BRANCH}
      - run: yyl all --isCommit --logLevel 2
