version: 2
jobs:
  build:
    docker:
      - image: jackness1208/yyl:latest

    filters:
      branches:
        only: master

    working_directory: ~/project

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "94:f5:9c:ec:49:b8:92:ad:18:10:16:55:49:f8:e5:a6"
      - run: yyl all --isCommit --logLevel 2
      - run: ssh-keyscan 114.215.151.192 >> ~/.ssh/known_hosts
      - run: scp ~/project/dist jackness@114.215.151.192:/www/www.jackness.org
